#!/usr/bin/env bash
# script to print all processes names containing bash with its pid 

if [ "$1" = "start" ]; then
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" = "stop" ]; then
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [ "$1" = "restart" ]; then
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process restarte"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
