#!/usr/bin/env bash
# loops scripts
# shellcheck disable=SC2034
h=1
while [ "$h" -le 13 ];
do
	i=1
	while [ "$i" -le 60 ];
	do
		if [ "$i" -eq 60 ] && [ "$h" -le 12 ];
		then
			echo "Hour: $((h++))"
		elif [ "$h" -eq 13 ];
		then 
			((++h))	
		elif [ "$i" -ne 60 ];
		then
			echo "$i"
		fi
		((++i))
	done
		
done
