#!/usr/bin/env bash
# loops scripts
# shellcheck disable=SC2034
h=0
while [ "$h" -lt 12 ];
do
	i=1
	while [ "$i" -le 60 ];
	do
		if [[ "$i" -eq 60 ]];
		then
			echo "Hour: $((++h))"
		else
			echo "$i"
		fi
		((++i))
	done
		
done
